### ISSUE TITLE
SWF Files to use

### ISSUE THREAD

**Issue by Flavorounet** [tr7zw/JavaOrbit#8]
Hi,

I see that you are working on a DarkOrbit emulator, great job from what i see ! But just a question, with which database and which .swf files does it works ?

**Comment by tr7zw** [comment]
Currently, it doesn't use a database or cms (yet), but for my local testing I use Azure as dummy cms/db, and Azure's client as 2d Revolution client. But currently I'm developing against an old 2009 client where I'm not too sure where I got it from(I just collected everything I could get my hands on, before it gets taken down). You can contact me on Discord (tr7zw#4005) and I can give you a complete setup for (in my case) xampp with working reloaded and 2009 client.
